Stop build if no place left for building
It complained "AttributeError: 'NoneType' object has no attribute 'rounded'" when my bot take every available places to build a structure. For example, if the bot had built main bases at all places with resources, it will be no more places for building a main base and near would be None which would cause the error